// Code generated by protoc-gen-go.
// source: organization.proto
// DO NOT EDIT!

/*
Package organization is a generated protocol buffer package.

It is generated from these files:
	organization.proto

It has these top-level messages:
	Request
	Organization
*/
package organization

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type Request_Action int32

const (
	Request_NEW   Request_Action = 0
	Request_INDEX Request_Action = 1
)

var Request_Action_name = map[int32]string{
	0: "NEW",
	1: "INDEX",
}
var Request_Action_value = map[string]int32{
	"NEW":   0,
	"INDEX": 1,
}

func (x Request_Action) String() string {
	return proto.EnumName(Request_Action_name, int32(x))
}

type Request struct {
	Action       Request_Action `protobuf:"varint,1,opt,name=action,enum=Request_Action" json:"action,omitempty"`
	Organization *Organization  `protobuf:"bytes,2,opt,name=organization" json:"organization,omitempty"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}

func (m *Request) GetOrganization() *Organization {
	if m != nil {
		return m.Organization
	}
	return nil
}

type Organization struct {
	Name  string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Error string `protobuf:"bytes,2,opt,name=error" json:"error,omitempty"`
}

func (m *Organization) Reset()         { *m = Organization{} }
func (m *Organization) String() string { return proto.CompactTextString(m) }
func (*Organization) ProtoMessage()    {}

func init() {
	proto.RegisterEnum("Request_Action", Request_Action_name, Request_Action_value)
}
